### ISSUE TITLE
Music player also?

### ISSUE THREAD

**Issue by Invictaz** [alpakeno/DePlayEnabler#1]
Can this also be enabled on the music player?

And what is the difference between your plugin and this one?

http://wololo.net/2019/10/12/psvita-release-videodebug-released-which-allows-the-videos-app-to-play-videos-directly-from-ux0-data-qcma-is-no-longer-needed-to-play-videos-in-the-native-app/

**Comment by GrapheneCt** [comment]
It's impossible for music player because it doesn't have debug mode (or rather, debug mode is there, but it is absolutely useless).

**Comment by Invictaz** [comment]
Thanks for the comment

**Comment by alpakeno** [comment]
@Invictaz 

As @GrapheneCt said, also VideoPlayer App is available in devkit which have this features.

Here is the differences:
1- This one is a user mode plugin.
2- Path for both sd0 and ux0 are changeable from configuration file.
3- You can use the root path e.g. ux0: or uma0: etc. to browse all folders.
4- Prevent the deletion of some unsupported video files when trying to play it.
